
#
# Optional Volumes:
#  - /opt/phabricator/conf - configuration
#  - /var/repo - code repos
#
#
#
version: "3.1"

services:
        phabricator:
                image: yesnault/docker-phabricator:latest
                networks:
                        - phabNetwork
                ports:
                        - "8081:80"
                links:
                        - database

        database:
                image: yesnault/docker-phabricator-mysql:latest
                networks:
                        - phabNetwork
networks:
 phabNetwork:
  name: phabNetwork