
#
# Optional Volumes:
#  - /opt/phabricator/conf - configuration
#  - /var/repo - code repos
#
#
#
version "3.1"

services:
        phabricator:
                image: joseamartinez/phabLab:1.0
                networks:
                        - phabNetwork
                ports:
                        - "8081:80"
                links:
                        database

        database:
                image: joseamartinez/phabDB:1.0
                networks:
                        - phabNetwork
